-- 2.a
SELECT TABLE_NAME FROM ALL_TABLES
WHERE OWNER = 'GILLES_HUBERT' AND TABLE_NAME LIKE 'TP3_%';

-- 2.b
SELECT * FROM GILLES_HUBERT.TP3_TA;
SELECT * FROM GILLES_HUBERT.TP3_TB;
SELECT * FROM GILLES_HUBERT.TP3_TC;
SELECT * FROM GILLES_HUBERT.TP3_TD;
SELECT * FROM GILLES_HUBERT.TP3_TE;
SELECT * FROM GILLES_HUBERT.TP3_TF;
SELECT * FROM GILLES_HUBERT.TP3_TG;

-- 2.c
DESC GILLES_HUBERT.TP3_TA;
DESC GILLES_HUBERT.TP3_TB;
DESC GILLES_HUBERT.TP3_TC;
DESC GILLES_HUBERT.TP3_TD;
DESC GILLES_HUBERT.TP3_TE;
DESC GILLES_HUBERT.TP3_TF;
DESC GILLES_HUBERT.TP3_TG;

-- 2.d
SELECT
    ALL_CONSTRAINTS.TABLE_NAME,
    ALL_CONS_COLUMNS.COLUMN_NAME,
    ALL_CONSTRAINTS.CONSTRAINT_NAME,
    ALL_CONSTRAINTS.R_CONSTRAINT_NAME,
    ALL_CONSTRAINTS.CONSTRAINT_TYPE,
    ALL_CONSTRAINTS.SEARCH_CONDITION,
    ALL_CONSTRAINTS.SEARCH_CONDITION_VC,
    ALL_CONSTRAINTS.DELETE_RULE
FROM ALL_CONSTRAINTS, ALL_CONS_COLUMNS
WHERE (
    ALL_CONSTRAINTS.OWNER = 'GILLES_HUBERT'
    AND ALL_CONS_COLUMNS.OWNER = ALL_CONSTRAINTS.OWNER
    AND ALL_CONSTRAINTS.TABLE_NAME IN ('TP3_TA', 'TP3_TB', 'TP3_TC', 'TP3_TD', 'TP3_TE', 'TP3_TF', 'TP3_TG')
    AND ALL_CONS_COLUMNS.TABLE_NAME = ALL_CONSTRAINTS.TABLE_NAME
    AND ALL_CONS_COLUMNS.CONSTRAINT_NAME = ALL_CONSTRAINTS.CONSTRAINT_NAME
);