-- 
-- TP n°3 - Partie n°2
-- 

-- 

-- 1.
SELECT * FROM GILLES_HUBERT.SRC1_MAGASINS;
SELECT * FROM GILLES_HUBERT.SRC1_VENDRE;
SELECT * FROM GILLES_HUBERT.SRC1_PRODUITS;
SELECT * FROM GILLES_HUBERT.SRC1_CATEGORIES;
SELECT * FROM GILLES_HUBERT.SRC1_ENSEIGNES;
SELECT * FROM GILLES_HUBERT.SRC1_MARQUES;

-- 2.
SELECT raisonSoc, tel FROM GILLES_HUBERT.SRC1_MAGASINS;

-- 3.
SELECT *
FROM GILLES_HUBERT.SRC1_MAGASINS
WHERE adrVille = 'Toulouse';

-- 4.
SELECT *
FROM GILLES_HUBERT.SRC1_MAGASINS
WHERE 33000 <= adrCP AND adrCP < 34000;

-- 5.
SELECT *
FROM GILLES_HUBERT.SRC1_PRODUITS
WHERE prixU = 1990;

-- 6.
SELECT *
FROM GILLES_HUBERT.SRC1_PRODUITS
WHERE prixU >= 2000;

-- 7.
SELECT *
FROM GILLES_HUBERT.SRC1_PRODUITS
WHERE 1000 <= prixU AND prixU <= 2000;

-- 8.
SELECT *
FROM GILLES_HUBERT.SRC1_PRODUITS
WHERE codeC IN (2, 4);

-- 9.
SELECT *
FROM GILLES_HUBERT.SRC1_VENDRE
WHERE dateV < TO_DATE('01/03/2000');

-- 10.
SELECT *
FROM GILLES_HUBERT.SRC1_VENDRE
WHERE TO_DATE('01/05/2000') <= dateV AND dateV < TO_DATE('01/06/2000');

-- 11.
SELECT P.codeP, P.desigP, M.desigM
FROM GILLES_HUBERT.SRC1_PRODUITS P, GILLES_HUBERT.SRC1_MARQUES M
WHERE P.codeM = M.codeM;

-- 12.
SELECT DISTINCT P.*, M.*
FROM
    GILLES_HUBERT.SRC1_VENDRE V,
    GILLES_HUBERT.SRC1_PRODUITS P,
    GILLES_HUBERT.SRC1_MARQUES M
WHERE
    TO_DATE('01/05/2000') <= V.dateV
    AND V.codeP = P.codeP
    AND P.codeM = M.codeM
;

-- 13.
SELECT DISTINCT Marque.*
FROM
    GILLES_HUBERT.SRC1_MAGASINS Magasin,
    GILLES_HUBERT.SRC1_VENDRE Vendre,
    GILLES_HUBERT.SRC1_PRODUITS Produit,
    GILLES_HUBERT.SRC1_MARQUES Marque
WHERE
    Magasin.adrVille = 'Pamiers'
    AND Vendre.raisonSoc = Magasin.raisonSoc
    AND Produit.codeP = Vendre.codeP
    AND Marque.codeM = Produit.codeM
;

-- 14.
SELECT DISTINCT Magasin.raisonSoc
FROM
    GILLES_HUBERT.SRC1_MAGASINS Magasin,
    GILLES_HUBERT.SRC1_CATEGORIES Categorie,
    GILLES_HUBERT.SRC1_MARQUES Marque,
    GILLES_HUBERT.SRC1_PRODUITS Produit,
    GILLES_HUBERT.SRC1_VENDRE Vendre
WHERE
    Categorie.desigC = 'téléviseur'
    AND Marque.desigM = 'Sony'
    AND Produit.codeC = Categorie.codeC
    AND Produit.codeM = Marque.codeM
    AND Vendre.codeP = Produit.codeP
    AND Magasin.raisonSoc = Vendre.raisonSoc
;

-- 

COMMIT;